https://www.graalvm.org/[GraalVM] is a new universal virtual machine from Oracle that supports a polyglot runtime environment and the ability to compile Java applications down to native machine code.

Any Micronaut application can be run using the GraalVM JVM, however special support has been added to Micronaut to support running Micronaut applications using https://www.graalvm.org/docs/reference-manual/aot-compilation/[GraalVM’s nativeimage tool].

We are going to modify the function project to be able to run it as Graal native image.

Create a copy of the function project.

`$ cp -r vies-vat-validator vies-vat-validat-graal`

Before the `jar` gradle task configure the `archivesBaseName` to be `vies-vat-validator`.

[source,groovy]
.vies-vat-validator-graal/build.gradle
----
include::{sourceDir}/vies-vat-validator-graal/build.gradle[tag=archivebasename]
----

The following steps were required:

=== 1. Install Graal

[source, bash]
----
sdk install java 1.0.0-rc-12-grl
sdk use java 1.0.0-rc-12-grl
----

NOTE: You may need to be in the latest version of http://sdkman.io[sdkman.io] to see Graal as a java candidate.

=== 2. Add Graal dependencies

Add the following to `build.gradle`:

[source,groovy]
.vies-vat-validator/build.gradle
----
include::{sourceDir}/vies-vat-validator-graal/build.gradle[tag=graaldependencies,indent=0]
----

=== 3. Add Graal Substitutions

Create `src/main/java/example/micronaut/MicronautSubstitutions.java`; a file needed to recompute Netty and Caffeine’s use of Unsafe.

[source,java]
.vies-vat-validator-graal/src/main/java/example/micronaut/MicronautSubstitutions.java
----
include::{sourceDir}/vies-vat-validator-graal/src/main/java/example/micronaut/MicronautSubstitutions.java[]
----

=== 4. Build the Function

[source,bash]
----
vies-vat-validator-graal $ ./gradlew assemble
----

=== 5. Generate a `reflect.json` file

Run the next command to to write out a `reflect.json`; a file computing the classloading requirements of the application.

[source,bash]
----
$ java -cp build/libs/vies-vat-validator-0.1-all.jar io.micronaut.graal.reflect.GraalClassLoadingAnalyzer
----

`reflect.json` file is written to destination: `build/reflect.json`

=== 6. Build the Graal Native Image

Run the `native-image` command. Create a bash script to encapsulate the execution of this command:

[source,bash]
.vies-vat-validator-graal/build-native-image.sh
----
include::{sourceDir}/vies-vat-validator-graal/build-native-image.sh[]
----

`vies-vat-validator-graal $ ./build-native-image.sh`

=== 7. Run the Native Function

The native function is now build. You can run it:

[source,bash]
----
complete/vies-vat-validator-graal $ time echo '{"memberStateCode":"es", "vatNumber":"B99286353"}' | ./vies-vat-validator
10:22:30.003 [main] DEBUG e.micronaut.ViesVatValidatorFunction - validate country: es vat number: B99286353
{"valid":true,"memberStateCode":"es","vatNumber":"B99286353"}
real    0m1.475s
user    0m0.017s
sys     0m0.034s
```
----

For comparision, execute with the jar file we generated in the previous section of this tutorial:

[source,bash]
----
complete/vies-vat-validator $ time echo '{"memberStateCode":"es", "vatNumber":"B99286353"}' | java -jar build/libs/vies-vat-validator-0.1-all.jar
10:25:52.136 [main] DEBUG e.micronaut.ViesVatValidatorFunction - validate country: es vat number: B99286353
{"memberStateCode":"es","vatNumber":"B99286353","valid":true}
real    0m3.261s
user    0m8.430s
sys     0m0.723s
----





