https://www.graalvm.org/[GraalVM] is a new universal virtual machine from Oracle that supports a polyglot runtime environment and the ability to compile Java applications down to native machine code.

Any Micronaut application can be run using the GraalVM JVM, however special support has been added to Micronaut to support running Micronaut applications using https://www.graalvm.org/docs/reference-manual/aot-compilation/[GraalVM’s nativeimage tool].

We are going to modify the function project to be able to run it as Graal native image.

Create a copy of the function project.

`$ cp -r vies-vat-validator vies-vat-validat-graal`

Before the `jar` gradle task configure the `archivesBaseName` to be `vies-vat-validator`.

[source,groovy]
.vies-vat-validator-graal/build.gradle
----
include::{sourceDir}/vies-vat-validator-graal/build.gradle[tag=archivebasename]
----

The following steps were required:

=== 1. Install Graal

[source, bash]
----
sdk install java 1.0.0-rc6-graal
sdk use java 1.0.0-rc6-graal
----

NOTE: You may need to be in the latest version of http://sdkman.io[sdkman.io] to see Graal as a java candidate.

=== 2. Install the SVM Dependency

Once you have installed the SDK you should make the svm dependency available via your local Maven cache. The easiest way to do this is via Maven’s install command:

[source, bash]
----
mvn install:install-file -Dfile=${JAVA_HOME}/jre/lib/svm/builder/svm.jar -DgroupId=com.oracle.substratevm -DartifactId=svm -Dversion=GraalVM-1.0.0-rc6 -Dpackaging=jar
----

=== 3. Update applications dependencies

Add the following to `build.gradle`:

[source,groovy]
.vies-vat-validator/build.gradle
----
include::{sourceDir}/vies-vat-validator-graal/build.gradle[tag=graaldependencies]
----

=== 4. Add Graal Substitutions

Create `src/main/java/example/micronaut/MicronautSubstitutions.java`; a file needed to recompute Netty and Caffeine’s use of Unsafe.

[source,groovy]
.vies-vat-validator-graal/src/main/java/example/micronaut/FunctionSubstitutions.java
----
include::{sourceDir}/vies-vat-validator-graal/src/main/java/example/micronaut/FunctionSubstitutions.java[]
----

=== 5. Build the Function

[source, groovy]
----
vies-vat-validator-graal $ ./gradlew assemble
----

=== 6. Generate a `reflect.json` file

Run the next command to to write out a `reflect.json`; a file computing the classloading requirements of the application.


```
vies-vat-validator-graal $ java -cp build/libs/vies-vat-validator-0.1-all.jar io.micronaut.graal.reflect.GraalClassLoadingAnalyzer
Graal Class Loading Analysis Enabled.
Writing reflect.json file to destination: build/reflect.json
```

=== 7. Build the Graal Native Image

Run the `native-image` command. Create a bash script to encapsulate the execution of this command:

[source,bash]
.vies-vat-validator/build-native-image.sh
----
include::{sourceDir}/vies-vat-validator-graal/build-native-image.sh[]
----

`vies-vat-validator-graal $ ./build-native-image.sh`

=== 8. Run the Native Function

The native function is now build. You can run it:

```
$ echo '{"memberStateCode":"es", "vatNumber":"B99286353"}' | ./vies-vat-validator
{"valid":true,"memberStateCode":"es","vatNumber":"B99286353"}
```