VIES (http://ec.europa.eu/taxation_customs/vies/faq.html[VAT Information Exchange System]) is an electronic mean of validating VAT-identification numbers of economic operators registered in the European Union for cross border transactions on goods or services.

For example, if you create an e-commerce Web application in the European union you would need to check the validity of the purchaser's
VAT Number in order to create a proper invoice.

To automate the validation checks, the EU does not offer a REST endpoint but a SOAP service. Its WSDL file can be obtained http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl[here].

**SOAP** (originally Simple Object Access Protocol) is a protocol specification for exchanging structured information in the implementation of web services in computer networks. Its purpose is to induce extensibility, neutrality and independence

Create `VatService` to do a SOAP request to validate the VAT Number.

To consume the SOAP service we could have use a SOAP library. However, the use case is so simple we are going to use the Micronaut HTTP Client and build
the SOAP envelope manually.

Add `http-client` dependency to `build.gradle`

[source,java]
.vies-vat-validator/build.gradle
----
include::{sourceDir}/vies-vat-validator/build.gradle[tag=http-client,indent=0]
----

Create a `VatService` which consumes the SOAP Service:

[source,java]
.vies-vat-validator/src/main/java/example/micronaut/VatService.java
----
include::{sourceDir}/vies-vat-validator/src/main/java/example/micronaut/VatService.java[]
----

<1> Use `javax.inject.Singleton` to designate a class a a singleton
<2> Constructor Injection of Micronaut RxClient
<3> Define a POST Request.
