Create an interface to abstract the collaboration with the function:

[source,java]
.invoice/src/main/java/example/micronaut/VatValidator.java
----
include::{sourceDir}/invoice/src/main/java/example/micronaut/VatValidator.java[]
----

Create two POJOs which are used by the previous interface:

[source,java]
.invoice/src/main/java/example/micronaut/VatValidationRequest.java
----
include::{sourceDir}/invoice/src/main/java/example/micronaut/VatValidationRequest.java[]
----

[source,java]
.invoice/src/main/java/example/micronaut/VatValidation.java
----
include::{sourceDir}/invoice/src/main/java/example/micronaut/VatValidation.java[]
----

Modify `build.gradle` to add `function-client` and `com.amazonaws:aws-java-sdk-lambda` dependencies:

[source,java]
.invoice/build.gradle
----
include::{sourceDir}/invoice/build.gradle[tag=function-client]
----

Also modify `src/main/resources/application.yml` and the define a function with the same name `vies-vat-validator` as the one we deployed to AWS Lambda:

[source,java]
.invoice/src/main/resources/application.yml
----
include::{sourceDir}/invoice/src/main/resources/application.yml[tag=aws]
----

Add the next configuration properties which we will use shortly:

[source,java]
.invoice/src/main/resources/application.yml
----
include::{sourceDir}/invoice/src/main/resources/application.yml[tag=vat]
----

Create `VatClient` to invoke our function:

[source,java]
.invoice/src/main/java/example/micronaut/VatClient.java
----
include::{sourceDir}/invoice/src/main/java/example/micronaut/VatClient.java[]
----

<1> The FunctionClient annotation allows applying introduction advise to an interface such that methods defined by the interface become invokers of remote functions configured by the application.
<2> You can remove a bean from the test classpath easily.
<3> Use the function name `vies-vat-validator`
<4> AWS Lambda functions may take time to warm up. Thus, failure is something you have to plan for and it is pretty common to want to attempt to retry an operation if it fails.
With https://docs.micronaut.io/snapshot/guide/index.html#retry[Micronaut Retry] you can try again easily.


